[application]
out_dir = "docs"

[web.app]
base_path = "dioxus-portfolio"
title = "Theo Guegan"

[web.resource]

[web.watcher]
index_on_404 = true

style = []

script = []

[web.resource.dev]

script = []
